name: Build Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'  # Vervang door de versie die je gebruikt

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --verbosity normal
